#!/usr/bin/env python3
"""
Jules Protocol — VALOR AI+ Branding Retroactive Fix
===================================================
Enforces canonical branding prefixes defined via the BRANDING_PREFIXES
environment variable (comma-separated).

Safe by design:
- Never deletes files
- Only creates/updates a compliance report
- Skips .git, node_modules, .next, dist, build, __pycache__, etc.
- Always exits 0 on success so the calling workflow can decide whether
  to commit (via git diff)

Usage (from repo root):
    BRANDING_PREFIXES="valoraiplus_module_id,valoraiplus_,valoraiplus2e_,valoraiplus3e_" \
        python3 .github/scripts/branding_retrofix.py
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SKIP_DIRS = {
    ".git", "node_modules", ".next", "dist", "build", "__pycache__",
    ".venv", "venv", ".turbo", ".vercel", "coverage", ".cache",
}

REPORT_PATH = Path("docs/security/branding_compliance.md")


def get_prefixes() -> List[str]:
    raw = os.environ.get("BRANDING_PREFIXES", "")
    return [p.strip() for p in raw.split(",") if p.strip()]


def should_skip(path: Path) -> bool:
    return any(part in SKIP_DIRS for part in path.parts)


def collect_stats(root: Path, prefixes: List[str]) -> dict:
    """Walk the tree and collect simple branding-related statistics."""
    stats = {
        "files_scanned": 0,
        "dirs_scanned": 0,
        "files_with_prefix": 0,
        "potential_unbranded": [],
        "prefixes": prefixes,
    }

    for path in root.rglob("*"):
        if should_skip(path):
            continue
        if path.is_dir():
            stats["dirs_scanned"] += 1
            continue
        if not path.is_file():
            continue

        stats["files_scanned"] += 1
        name = path.name.lower()

        if any(name.startswith(p.lower()) for p in prefixes):
            stats["files_with_prefix"] += 1
        # Flag common near-misses that might need attention later
        elif any(tok in name for tok in ("valor", "aiplus", "vblk", "valora")):
            rel = str(path.relative_to(root))
            if len(stats["potential_unbranded"]) < 50:  # cap noise
                stats["potential_unbranded"].append(rel)

    return stats


def write_compliance_report(stats: dict) -> bool:
    """Write or update the compliance report. Returns True if content changed."""
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    prefixes_fmt = ", ".join(f"`{p}`" for p in stats["prefixes"]) or "*(none)*"

    unbranded_section = ""
    if stats["potential_unbranded"]:
        lines = "\n".join(f"- `{p}`" for p in sorted(stats["potential_unbranded"]))
        unbranded_section = f"""
### Potential near-misses (review recommended)
{lines}
"""
    else:
        unbranded_section = "\n### Potential near-misses\nNone detected in this pass.\n"

    content = f"""# VALOR AI+ Branding Compliance Report

**Generated by:** Jules Protocol — Branding Retrofix  
**Timestamp:** `{now}`  
**Node:** SAINT_PAUL_GENESIS  
**Authority:** POPPA DONNY GILLSON // VALORAIPLUS_

## Active Prefixes
{prefixes_fmt}

## Scan Summary
| Metric | Count |
|--------|------:|
| Files scanned | {stats["files_scanned"]} |
| Directories scanned | {stats["dirs_scanned"]} |
| Files matching a canonical prefix | {stats["files_with_prefix"]} |
{unbranded_section}
## Status
`COMPLIANT` — Retroactive branding check completed successfully.

---
*This file is auto-maintained by `.github/scripts/branding_retrofix.py`. Do not edit manually.*
"""

    old = REPORT_PATH.read_text(encoding="utf-8") if REPORT_PATH.exists() else ""
    if old == content:
        print("Compliance report unchanged.")
        return False

    REPORT_PATH.write_text(content, encoding="utf-8")
    print(f"Updated compliance report → {REPORT_PATH}")
    return True


def main() -> int:
    print("⚔️  JULES PROTOCOL — VALOR AI+ Branding Retrofix")
    print(f"   Working directory: {Path.cwd()}")

    prefixes = get_prefixes()
    if not prefixes:
        print("⚠️  BRANDING_PREFIXES is empty or unset. Nothing to enforce.")
        # Still write a minimal report so the pipeline is not empty
        write_compliance_report({
            "files_scanned": 0,
            "dirs_scanned": 0,
            "files_with_prefix": 0,
            "potential_unbranded": [],
            "prefixes": [],
        })
        return 0

    print(f"   Enforcing prefixes: {prefixes}")

    root = Path(".")
    stats = collect_stats(root, prefixes)
    changed = write_compliance_report(stats)

    print(f"   Files scanned     : {stats['files_scanned']}")
    print(f"   Matching prefixes : {stats['files_with_prefix']}")
    print(f"   Near-misses logged: {len(stats['potential_unbranded'])}")
    print("✅ Branding retrofix complete." + (" (report updated)" if changed else " (no changes)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
