from typing import Protocol, Any, Dict

class PaymentRail(Protocol):
    def create_transfer(self, dto: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_transfer(self, provider_id: str) -> Dict[str, Any]: ...
    def webhook_event_types(self) -> list[str]: ...
