// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title VALORAIPLUSQuantumAnchors
 * @author NEWT, Supreme Commander
 * @notice This contract anchors multi-hash proofs generated by the VALORAIPLUS®️
 * Voyager-Enterprise Quantum Security Suite. It serves as the immutable on-chain
 * record for sovereign artifacts, secured by VALORCHAIN_G.
 */
contract VALORAIPLUSQuantumAnchors is Ownable {

    struct QuantumProof {
        bytes32 keccak256Hash;
        bytes32 blake2bHash;    // Stored as bytes32 for on-chain efficiency
        bytes kyberCiphertext;  // Variable size for post-quantum algorithm flexibility
        string ipfsMetadataCid; // Link to the full metadata package on IPFS
    }

    // Mapping from an artifact ID to its on-chain quantum proof
    mapping(bytes32 => QuantumProof) public anchoredProofs;

    // Event emitted upon successful anchoring of a new proof
    event ArtifactAnchored(
        bytes32 indexed artifactId,
        address indexed anchorer,
        string ipfsMetadataCid,
        uint256 timestamp
    );

    /**
     * @dev Throws if called by any account other than the owner.
     */
    constructor(address initialOwner) Ownable(initialOwner) {}

    /**
     * @notice Anchors a new quantum proof to the blockchain.
     * @dev This function can only be called by the contract owner (the Unified CLI).
     * @param artifactId A unique identifier for the artifact being anchored.
     * @param keccak256Hash The keccak256 hash of the artifact.
     * @param blake2bHash The BLAKE2b hash of the artifact.
     * @param kyberCiphertext The Kyber Crystals simulated ciphertext.
     * @param ipfsMetadataCid The IPFS CID for the full metadata package.
     */
    function anchorProof(
        bytes32 artifactId,
        bytes32 keccak256Hash,
        bytes32 blake2bHash,
        bytes calldata kyberCiphertext,
        string calldata ipfsMetadataCid
    ) external onlyOwner {
        require(anchoredProofs[artifactId].keccak256Hash == 0, "Artifact already anchored");

        anchoredProofs[artifactId] = QuantumProof({
            keccak256Hash: keccak256Hash,
            blake2bHash: blake2bHash,
            kyberCiphertext: kyberCiphertext,
            ipfsMetadataCid: ipfsMetadataCid
        });

        emit ArtifactAnchored(
            artifactId,
            msg.sender,
            ipfsMetadataCid,
            block.timestamp
        );
    }

    /**
     * @notice Retrieves the anchored proof for a given artifact ID.
     * @param artifactId The ID of the artifact to retrieve.
     * @return The stored QuantumProof struct.
     */
    function getProof(bytes32 artifactId) external view returns (QuantumProof memory) {
        return anchoredProofs[artifactId];
    }
}